### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by RealXiaoLin** [RealXiaoLin/furima-31987#13]
# フリマアプリのURL
https://furima-31987.herokuapp.com/
# Basic認証
- ID
xiaolin
- パスワード
5884
#  出品者アカウント情報
 - メールアドレス
test15@test.com
 - パスワード
aaa111
# 購入者アカウント情報
 - メールアドレス
test16@test.com
 - パスワード
aaa111
# 購入用カード情報
- 番号
4242424242424242
- 期限
12/23
- セキュリティコード
123

**Comment by mo1015** [comment]
小林さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by RealXiaoLin** [comment]
> 小林さん、ご提出ありがとうございます！
> 挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
> おめでとうございます！
> **※確認したのは必須機能のみで追加実装した機能については確認していません。 そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

早速のご確認、誠にありがとうございました。
